name: Deploy infrastructure changes
on:
  repository_dispatch:
    types: [deploy-command]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: base
        run: |
          echo "${{ joJson(github.event) }}"
      - name: base2
        run: |
          echo "${{ joJson(github.event) }}"
      
      - name: Validate cluster order
        run: |
          echo """${{ toJson(github) }}"""      
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: rocket
      - name: Validate cluster order
        run: |
          echo """${{ toJson(github.event) }}"""
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
      