name: Deploy infrastructure changes
on:
  repository_dispatch:
    types: [deploy-command]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Verify that feature only merges to develop and develop to production.
      - name: base
        run: |
          echo "${{ github.event.client_payload.pull_request.head.ref }}"
          echo "${{ github.event.client_payload.pull_request.base.ref }}"
          echo "${{ github.event.client_payload.slash_command.args.all }}"

      # If develop to production and cluster != dev verify that previous env was successful
      # unless override was passed in.
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          direction: last
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body-includes: "check12 successfully deployed"
          #body-includes: ${{ github.event.client_payload.github.payload.slash_command.args.all }}
      - run: |
          echo """${{ toJson(steps.fc.outputs.comment-id) }}"""

      # Send update comment with +1 before starting to apply
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: "+1"

      # Run the apply step

      # Add successful comment if apply was successful
      - name: Create success comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.client_payload.pull_request.number }}
          body: |
            ${{ github.event.client_payload.slash_command.args.all }} successfully deployed
          reactions: hooray
      # Add comment if it failed
      - name: Create failed comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.client_payload.pull_request.number }}
          body: |
            ${{ github.event.client_payload.slash_command.args.all }} apply failed
          reactions: confused