name: Deploy infrastructure changes
on:
  repository_dispatch:
    types: [deploy-command]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: base
        run: |
          echo "${{ github.event.client_payload.pull_request.head.ref }}"
          echo "${{ github.event.client_payload.pull_request.base.ref }}"
          echo "${{ github.event.client_payload.github.payload.slash_command.args.all }}"
      - name: Validate cluster order
        run: |
          echo """${{ toJson(github) }}"""
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          direction: last
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body-includes: "check5"
          #body-includes: ${{ github.event.client_payload.github.payload.slash_command.args.all }}
      - run: |
          echo ${{ steps.fc.outputs.comment-id }}
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: "+1"
      - name: Validate cluster order
        run: |
          echo """${{ toJson(github.event) }}"""
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray