name: Build and Deploy to GKE
on:
  release:
    types: [published]
jobs:
  validate:
    name: Validate merging order
    runs-on: ubuntu-latest
    steps:
    - name: step one
      run: echo ${{ toJson(github.event) }}