name: Build and Deploy to GKE
on:
  - push
jobs:
  getDashboard:
    name: Download dasboard
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Get dashboards
      run: |
        for value in $(jq -j '.[] | "\(.name):\(.id)\n"' metrics/dashboardgroups.json); do
          name=$(echo $value | cut -d ':' -f 1)
          id=$(echo $value | cut -d ':' -f 2)
          curl -H "X-SF-TOKEN: ${{ secrets.SIGNALFX_TOKEN }}" https://ingka.signalfx.com/v2/dashboardgroup/${id}/export > metrics/${name}.json
        done
    - name: Commit changes
      uses: actions-js/push@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: metrics