name: Build and Deploy to GKE
on:
  - push
env:
  ENDPOINT: https://api.eu0.signalfx.com.
jobs:
  getDashboard:
    name: Download dasboard
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: get dashboard
      run: |
        for group in $(cat dashboardgroups); do 
          curl -H "X_SF_TOKEN: ${{ secrets.SIGNALFX_TOKEN }}" https://ingka.signalfx.com/v2/dashboardgroup/${group}/export > ${group}.json
        done