name: Build and Deploy to GKE
on:
  - push
env:
  ENDPOINT: https://api.eu0.signalfx.com.
jobs:
  getDashboard:
    name: Download dasboard
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: get dashboard
      run: |
        for group in $(cat metrics/dashboardgroups); do 
          curl -H "X_SF_TOKEN: ${{ secrets.SIGNALFX_TOKEN }}" https://ingka.signalfx.com/v2/dashboardgroup/${group}/export > metrics/${group}.json
        done
    - name: Commit changes
      uses: actions-js/push@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: 'Automatically fetched changes: ${date}'
        directory: metrics